// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v5.29.4
// source: proto/operate-service/operate-service.proto

package operate_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateSystemCustomTabReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrgId  string `protobuf:"bytes,1,opt,name=orgId,proto3" json:"orgId,omitempty"`   // 租户ID
	UserId string `protobuf:"bytes,2,opt,name=userId,proto3" json:"userId,omitempty"` // 用户ID
	Mode   string `protobuf:"bytes,3,opt,name=mode,proto3" json:"mode,omitempty"`     // 模式
	Tab    *Tab   `protobuf:"bytes,4,opt,name=tab,proto3" json:"tab,omitempty"`       // 标签页信息
}

func (x *CreateSystemCustomTabReq) Reset() {
	*x = CreateSystemCustomTabReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_operate_service_operate_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateSystemCustomTabReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSystemCustomTabReq) ProtoMessage() {}

func (x *CreateSystemCustomTabReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_operate_service_operate_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSystemCustomTabReq.ProtoReflect.Descriptor instead.
func (*CreateSystemCustomTabReq) Descriptor() ([]byte, []int) {
	return file_proto_operate_service_operate_service_proto_rawDescGZIP(), []int{0}
}

func (x *CreateSystemCustomTabReq) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *CreateSystemCustomTabReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateSystemCustomTabReq) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *CreateSystemCustomTabReq) GetTab() *Tab {
	if x != nil {
		return x.Tab
	}
	return nil
}

type CreateSystemCustomLoginReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrgId  string `protobuf:"bytes,1,opt,name=orgId,proto3" json:"orgId,omitempty"`   // 租户ID
	UserId string `protobuf:"bytes,2,opt,name=userId,proto3" json:"userId,omitempty"` // 用户ID
	Mode   string `protobuf:"bytes,3,opt,name=mode,proto3" json:"mode,omitempty"`
	Login  *Login `protobuf:"bytes,4,opt,name=login,proto3" json:"login,omitempty"` // 登录页
}

func (x *CreateSystemCustomLoginReq) Reset() {
	*x = CreateSystemCustomLoginReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_operate_service_operate_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateSystemCustomLoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSystemCustomLoginReq) ProtoMessage() {}

func (x *CreateSystemCustomLoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_operate_service_operate_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSystemCustomLoginReq.ProtoReflect.Descriptor instead.
func (*CreateSystemCustomLoginReq) Descriptor() ([]byte, []int) {
	return file_proto_operate_service_operate_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreateSystemCustomLoginReq) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *CreateSystemCustomLoginReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateSystemCustomLoginReq) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *CreateSystemCustomLoginReq) GetLogin() *Login {
	if x != nil {
		return x.Login
	}
	return nil
}

type CreateSystemCustomHomeReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrgId  string `protobuf:"bytes,1,opt,name=orgId,proto3" json:"orgId,omitempty"`   // 租户ID
	UserId string `protobuf:"bytes,2,opt,name=userId,proto3" json:"userId,omitempty"` // 用户ID
	Mode   string `protobuf:"bytes,3,opt,name=mode,proto3" json:"mode,omitempty"`
	Home   *Home  `protobuf:"bytes,4,opt,name=home,proto3" json:"home,omitempty"` // 标题
}

func (x *CreateSystemCustomHomeReq) Reset() {
	*x = CreateSystemCustomHomeReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_operate_service_operate_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateSystemCustomHomeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSystemCustomHomeReq) ProtoMessage() {}

func (x *CreateSystemCustomHomeReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_operate_service_operate_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSystemCustomHomeReq.ProtoReflect.Descriptor instead.
func (*CreateSystemCustomHomeReq) Descriptor() ([]byte, []int) {
	return file_proto_operate_service_operate_service_proto_rawDescGZIP(), []int{2}
}

func (x *CreateSystemCustomHomeReq) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *CreateSystemCustomHomeReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateSystemCustomHomeReq) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *CreateSystemCustomHomeReq) GetHome() *Home {
	if x != nil {
		return x.Home
	}
	return nil
}

type GetSystemCustomReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mode string `protobuf:"bytes,1,opt,name=mode,proto3" json:"mode,omitempty"` // 模式
}

func (x *GetSystemCustomReq) Reset() {
	*x = GetSystemCustomReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_operate_service_operate_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSystemCustomReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSystemCustomReq) ProtoMessage() {}

func (x *GetSystemCustomReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_operate_service_operate_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSystemCustomReq.ProtoReflect.Descriptor instead.
func (*GetSystemCustomReq) Descriptor() ([]byte, []int) {
	return file_proto_operate_service_operate_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetSystemCustomReq) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

type SystemCustom struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Login *Login `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"` // 登录页
	Tab   *Tab   `protobuf:"bytes,2,opt,name=tab,proto3" json:"tab,omitempty"`     // logo
	Home  *Home  `protobuf:"bytes,3,opt,name=home,proto3" json:"home,omitempty"`   // 标题
}

func (x *SystemCustom) Reset() {
	*x = SystemCustom{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_operate_service_operate_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SystemCustom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemCustom) ProtoMessage() {}

func (x *SystemCustom) ProtoReflect() protoreflect.Message {
	mi := &file_proto_operate_service_operate_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemCustom.ProtoReflect.Descriptor instead.
func (*SystemCustom) Descriptor() ([]byte, []int) {
	return file_proto_operate_service_operate_service_proto_rawDescGZIP(), []int{4}
}

func (x *SystemCustom) GetLogin() *Login {
	if x != nil {
		return x.Login
	}
	return nil
}

func (x *SystemCustom) GetTab() *Tab {
	if x != nil {
		return x.Tab
	}
	return nil
}

func (x *SystemCustom) GetHome() *Home {
	if x != nil {
		return x.Home
	}
	return nil
}

type Tab struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TabLogoPath string `protobuf:"bytes,1,opt,name=tabLogoPath,proto3" json:"tabLogoPath,omitempty"` // 标签页logo路径
	TabTitle    string `protobuf:"bytes,2,opt,name=tabTitle,proto3" json:"tabTitle,omitempty"`       // 标签页标题
}

func (x *Tab) Reset() {
	*x = Tab{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_operate_service_operate_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Tab) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tab) ProtoMessage() {}

func (x *Tab) ProtoReflect() protoreflect.Message {
	mi := &file_proto_operate_service_operate_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tab.ProtoReflect.Descriptor instead.
func (*Tab) Descriptor() ([]byte, []int) {
	return file_proto_operate_service_operate_service_proto_rawDescGZIP(), []int{5}
}

func (x *Tab) GetTabLogoPath() string {
	if x != nil {
		return x.TabLogoPath
	}
	return ""
}

func (x *Tab) GetTabTitle() string {
	if x != nil {
		return x.TabTitle
	}
	return ""
}

type Login struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LoginBgPath      string `protobuf:"bytes,1,opt,name=loginBgPath,proto3" json:"loginBgPath,omitempty"`           // 登录页背景图
	LoginLogo        string `protobuf:"bytes,2,opt,name=loginLogo,proto3" json:"loginLogo,omitempty"`               // 登录页logo路径
	LoginWelcomeText string `protobuf:"bytes,3,opt,name=loginWelcomeText,proto3" json:"loginWelcomeText,omitempty"` // 登录页欢迎词
	LoginButtonColor string `protobuf:"bytes,4,opt,name=loginButtonColor,proto3" json:"loginButtonColor,omitempty"` // 登录按钮颜色
}

func (x *Login) Reset() {
	*x = Login{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_operate_service_operate_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Login) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Login) ProtoMessage() {}

func (x *Login) ProtoReflect() protoreflect.Message {
	mi := &file_proto_operate_service_operate_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Login.ProtoReflect.Descriptor instead.
func (*Login) Descriptor() ([]byte, []int) {
	return file_proto_operate_service_operate_service_proto_rawDescGZIP(), []int{6}
}

func (x *Login) GetLoginBgPath() string {
	if x != nil {
		return x.LoginBgPath
	}
	return ""
}

func (x *Login) GetLoginLogo() string {
	if x != nil {
		return x.LoginLogo
	}
	return ""
}

func (x *Login) GetLoginWelcomeText() string {
	if x != nil {
		return x.LoginWelcomeText
	}
	return ""
}

func (x *Login) GetLoginButtonColor() string {
	if x != nil {
		return x.LoginButtonColor
	}
	return ""
}

type Home struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HomeLogoPath string `protobuf:"bytes,1,opt,name=homeLogoPath,proto3" json:"homeLogoPath,omitempty"` // 平台logo路径
	HomeName     string `protobuf:"bytes,2,opt,name=homeName,proto3" json:"homeName,omitempty"`         // 平台名称
	HomeBgColor  string `protobuf:"bytes,3,opt,name=homeBgColor,proto3" json:"homeBgColor,omitempty"`   // 平台背景颜色
}

func (x *Home) Reset() {
	*x = Home{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_operate_service_operate_service_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Home) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Home) ProtoMessage() {}

func (x *Home) ProtoReflect() protoreflect.Message {
	mi := &file_proto_operate_service_operate_service_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Home.ProtoReflect.Descriptor instead.
func (*Home) Descriptor() ([]byte, []int) {
	return file_proto_operate_service_operate_service_proto_rawDescGZIP(), []int{7}
}

func (x *Home) GetHomeLogoPath() string {
	if x != nil {
		return x.HomeLogoPath
	}
	return ""
}

func (x *Home) GetHomeName() string {
	if x != nil {
		return x.HomeName
	}
	return ""
}

func (x *Home) GetHomeBgColor() string {
	if x != nil {
		return x.HomeBgColor
	}
	return ""
}

type AddClientRecordReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientId string `protobuf:"bytes,1,opt,name=clientId,proto3" json:"clientId,omitempty"`
}

func (x *AddClientRecordReq) Reset() {
	*x = AddClientRecordReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_operate_service_operate_service_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddClientRecordReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddClientRecordReq) ProtoMessage() {}

func (x *AddClientRecordReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_operate_service_operate_service_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddClientRecordReq.ProtoReflect.Descriptor instead.
func (*AddClientRecordReq) Descriptor() ([]byte, []int) {
	return file_proto_operate_service_operate_service_proto_rawDescGZIP(), []int{8}
}

func (x *AddClientRecordReq) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

type GetClientOverviewReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StartDate string `protobuf:"bytes,1,opt,name=startDate,proto3" json:"startDate,omitempty"`
	EndDate   string `protobuf:"bytes,2,opt,name=endDate,proto3" json:"endDate,omitempty"`
}

func (x *GetClientOverviewReq) Reset() {
	*x = GetClientOverviewReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_operate_service_operate_service_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetClientOverviewReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClientOverviewReq) ProtoMessage() {}

func (x *GetClientOverviewReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_operate_service_operate_service_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClientOverviewReq.ProtoReflect.Descriptor instead.
func (*GetClientOverviewReq) Descriptor() ([]byte, []int) {
	return file_proto_operate_service_operate_service_proto_rawDescGZIP(), []int{9}
}

func (x *GetClientOverviewReq) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *GetClientOverviewReq) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

type GetClientTrendReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StartDate string `protobuf:"bytes,1,opt,name=startDate,proto3" json:"startDate,omitempty"`
	EndDate   string `protobuf:"bytes,2,opt,name=endDate,proto3" json:"endDate,omitempty"`
}

func (x *GetClientTrendReq) Reset() {
	*x = GetClientTrendReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_operate_service_operate_service_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetClientTrendReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClientTrendReq) ProtoMessage() {}

func (x *GetClientTrendReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_operate_service_operate_service_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClientTrendReq.ProtoReflect.Descriptor instead.
func (*GetClientTrendReq) Descriptor() ([]byte, []int) {
	return file_proto_operate_service_operate_service_proto_rawDescGZIP(), []int{10}
}

func (x *GetClientTrendReq) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *GetClientTrendReq) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

type GetCumulativeClientOverviewReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EndAt string `protobuf:"bytes,1,opt,name=endAt,proto3" json:"endAt,omitempty"`
}

func (x *GetCumulativeClientOverviewReq) Reset() {
	*x = GetCumulativeClientOverviewReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_operate_service_operate_service_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCumulativeClientOverviewReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCumulativeClientOverviewReq) ProtoMessage() {}

func (x *GetCumulativeClientOverviewReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_operate_service_operate_service_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCumulativeClientOverviewReq.ProtoReflect.Descriptor instead.
func (*GetCumulativeClientOverviewReq) Descriptor() ([]byte, []int) {
	return file_proto_operate_service_operate_service_proto_rawDescGZIP(), []int{11}
}

func (x *GetCumulativeClientOverviewReq) GetEndAt() string {
	if x != nil {
		return x.EndAt
	}
	return ""
}

type ClientOverviewItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value            float32 `protobuf:"fixed32,1,opt,name=value,proto3" json:"value,omitempty"`
	PeriodOverperiod float32 `protobuf:"fixed32,2,opt,name=periodOverperiod,proto3" json:"periodOverperiod,omitempty"`
}

func (x *ClientOverviewItem) Reset() {
	*x = ClientOverviewItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_operate_service_operate_service_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientOverviewItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientOverviewItem) ProtoMessage() {}

func (x *ClientOverviewItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_operate_service_operate_service_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientOverviewItem.ProtoReflect.Descriptor instead.
func (*ClientOverviewItem) Descriptor() ([]byte, []int) {
	return file_proto_operate_service_operate_service_proto_rawDescGZIP(), []int{12}
}

func (x *ClientOverviewItem) GetValue() float32 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *ClientOverviewItem) GetPeriodOverperiod() float32 {
	if x != nil {
		return x.PeriodOverperiod
	}
	return 0
}

type ClientOverViewInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ActiveClient   *ClientOverviewItem `protobuf:"bytes,1,opt,name=activeClient,proto3" json:"activeClient,omitempty"`
	TotalClient    *ClientOverviewItem `protobuf:"bytes,2,opt,name=totalClient,proto3" json:"totalClient,omitempty"`
	AdditionClient *ClientOverviewItem `protobuf:"bytes,3,opt,name=additionClient,proto3" json:"additionClient,omitempty"`
}

func (x *ClientOverViewInfo) Reset() {
	*x = ClientOverViewInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_operate_service_operate_service_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientOverViewInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientOverViewInfo) ProtoMessage() {}

func (x *ClientOverViewInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_operate_service_operate_service_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientOverViewInfo.ProtoReflect.Descriptor instead.
func (*ClientOverViewInfo) Descriptor() ([]byte, []int) {
	return file_proto_operate_service_operate_service_proto_rawDescGZIP(), []int{13}
}

func (x *ClientOverViewInfo) GetActiveClient() *ClientOverviewItem {
	if x != nil {
		return x.ActiveClient
	}
	return nil
}

func (x *ClientOverViewInfo) GetTotalClient() *ClientOverviewItem {
	if x != nil {
		return x.TotalClient
	}
	return nil
}

func (x *ClientOverViewInfo) GetAdditionClient() *ClientOverviewItem {
	if x != nil {
		return x.AdditionClient
	}
	return nil
}

type ClientTrendInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Client *StatisticChart `protobuf:"bytes,1,opt,name=client,proto3" json:"client,omitempty"`
}

func (x *ClientTrendInfo) Reset() {
	*x = ClientTrendInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_operate_service_operate_service_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientTrendInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientTrendInfo) ProtoMessage() {}

func (x *ClientTrendInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_operate_service_operate_service_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientTrendInfo.ProtoReflect.Descriptor instead.
func (*ClientTrendInfo) Descriptor() ([]byte, []int) {
	return file_proto_operate_service_operate_service_proto_rawDescGZIP(), []int{14}
}

func (x *ClientTrendInfo) GetClient() *StatisticChart {
	if x != nil {
		return x.Client
	}
	return nil
}

type StatisticChart struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TableName  string                `protobuf:"bytes,1,opt,name=tableName,proto3" json:"tableName,omitempty"`
	ChartLines []*StatisticChartLine `protobuf:"bytes,2,rep,name=chartLines,proto3" json:"chartLines,omitempty"`
}

func (x *StatisticChart) Reset() {
	*x = StatisticChart{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_operate_service_operate_service_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatisticChart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatisticChart) ProtoMessage() {}

func (x *StatisticChart) ProtoReflect() protoreflect.Message {
	mi := &file_proto_operate_service_operate_service_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatisticChart.ProtoReflect.Descriptor instead.
func (*StatisticChart) Descriptor() ([]byte, []int) {
	return file_proto_operate_service_operate_service_proto_rawDescGZIP(), []int{15}
}

func (x *StatisticChart) GetTableName() string {
	if x != nil {
		return x.TableName
	}
	return ""
}

func (x *StatisticChart) GetChartLines() []*StatisticChartLine {
	if x != nil {
		return x.ChartLines
	}
	return nil
}

type StatisticChartLine struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LineName string                    `protobuf:"bytes,1,opt,name=lineName,proto3" json:"lineName,omitempty"`
	Items    []*StatisticChartLineItem `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *StatisticChartLine) Reset() {
	*x = StatisticChartLine{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_operate_service_operate_service_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatisticChartLine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatisticChartLine) ProtoMessage() {}

func (x *StatisticChartLine) ProtoReflect() protoreflect.Message {
	mi := &file_proto_operate_service_operate_service_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatisticChartLine.ProtoReflect.Descriptor instead.
func (*StatisticChartLine) Descriptor() ([]byte, []int) {
	return file_proto_operate_service_operate_service_proto_rawDescGZIP(), []int{16}
}

func (x *StatisticChartLine) GetLineName() string {
	if x != nil {
		return x.LineName
	}
	return ""
}

func (x *StatisticChartLine) GetItems() []*StatisticChartLineItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type StatisticChartLineItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string  `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value float32 `protobuf:"fixed32,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *StatisticChartLineItem) Reset() {
	*x = StatisticChartLineItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_operate_service_operate_service_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatisticChartLineItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatisticChartLineItem) ProtoMessage() {}

func (x *StatisticChartLineItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_operate_service_operate_service_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatisticChartLineItem.ProtoReflect.Descriptor instead.
func (*StatisticChartLineItem) Descriptor() ([]byte, []int) {
	return file_proto_operate_service_operate_service_proto_rawDescGZIP(), []int{17}
}

func (x *StatisticChartLineItem) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *StatisticChartLineItem) GetValue() float32 {
	if x != nil {
		return x.Value
	}
	return 0
}

var File_proto_operate_service_operate_service_proto protoreflect.FileDescriptor

var file_proto_operate_service_operate_service_proto_rawDesc = []byte{
	0x0a, 0x2b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x65, 0x2d,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x65, 0x2d,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x6f,
	0x70, 0x65, 0x72, 0x61, 0x74, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x1a, 0x1b,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f,
	0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x84, 0x01, 0x0a, 0x18,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x43, 0x75, 0x73, 0x74,
	0x6f, 0x6d, 0x54, 0x61, 0x62, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x6f, 0x72, 0x67, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6f, 0x72, 0x67, 0x49, 0x64, 0x12, 0x16,
	0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x12, 0x26, 0x0a, 0x03, 0x74, 0x61,
	0x62, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74,
	0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x54, 0x61, 0x62, 0x52, 0x03, 0x74,
	0x61, 0x62, 0x22, 0x8c, 0x01, 0x0a, 0x1a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x79, 0x73,
	0x74, 0x65, 0x6d, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65,
	0x71, 0x12, 0x14, 0x0a, 0x05, 0x6f, 0x72, 0x67, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x6f, 0x72, 0x67, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6d,
	0x6f, 0x64, 0x65, 0x12, 0x2c, 0x0a, 0x05, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x16, 0x2e, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x65, 0x5f, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x05, 0x6c, 0x6f, 0x67, 0x69,
	0x6e, 0x22, 0x88, 0x01, 0x0a, 0x19, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x79, 0x73, 0x74,
	0x65, 0x6d, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x48, 0x6f, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x12,
	0x14, 0x0a, 0x05, 0x6f, 0x72, 0x67, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x6f, 0x72, 0x67, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x6d, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6d, 0x6f, 0x64,
	0x65, 0x12, 0x29, 0x0a, 0x04, 0x68, 0x6f, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x15, 0x2e, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x48, 0x6f, 0x6d, 0x65, 0x52, 0x04, 0x68, 0x6f, 0x6d, 0x65, 0x22, 0x28, 0x0a, 0x12,
	0x47, 0x65, 0x74, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x52,
	0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x22, 0x8f, 0x01, 0x0a, 0x0c, 0x53, 0x79, 0x73, 0x74, 0x65,
	0x6d, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x12, 0x2c, 0x0a, 0x05, 0x6c, 0x6f, 0x67, 0x69, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x65,
	0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x05,
	0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x26, 0x0a, 0x03, 0x74, 0x61, 0x62, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x65, 0x5f, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x54, 0x61, 0x62, 0x52, 0x03, 0x74, 0x61, 0x62, 0x12, 0x29, 0x0a,
	0x04, 0x68, 0x6f, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x6f, 0x70,
	0x65, 0x72, 0x61, 0x74, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x48, 0x6f,
	0x6d, 0x65, 0x52, 0x04, 0x68, 0x6f, 0x6d, 0x65, 0x22, 0x43, 0x0a, 0x03, 0x54, 0x61, 0x62, 0x12,
	0x20, 0x0a, 0x0b, 0x74, 0x61, 0x62, 0x4c, 0x6f, 0x67, 0x6f, 0x50, 0x61, 0x74, 0x68, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x74, 0x61, 0x62, 0x4c, 0x6f, 0x67, 0x6f, 0x50, 0x61, 0x74,
	0x68, 0x12, 0x1a, 0x0a, 0x08, 0x74, 0x61, 0x62, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x61, 0x62, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x22, 0x9f, 0x01,
	0x0a, 0x05, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x20, 0x0a, 0x0b, 0x6c, 0x6f, 0x67, 0x69, 0x6e,
	0x42, 0x67, 0x50, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6c, 0x6f,
	0x67, 0x69, 0x6e, 0x42, 0x67, 0x50, 0x61, 0x74, 0x68, 0x12, 0x1c, 0x0a, 0x09, 0x6c, 0x6f, 0x67,
	0x69, 0x6e, 0x4c, 0x6f, 0x67, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6c, 0x6f,
	0x67, 0x69, 0x6e, 0x4c, 0x6f, 0x67, 0x6f, 0x12, 0x2a, 0x0a, 0x10, 0x6c, 0x6f, 0x67, 0x69, 0x6e,
	0x57, 0x65, 0x6c, 0x63, 0x6f, 0x6d, 0x65, 0x54, 0x65, 0x78, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x10, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x57, 0x65, 0x6c, 0x63, 0x6f, 0x6d, 0x65, 0x54,
	0x65, 0x78, 0x74, 0x12, 0x2a, 0x0a, 0x10, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x42, 0x75, 0x74, 0x74,
	0x6f, 0x6e, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x6c,
	0x6f, 0x67, 0x69, 0x6e, 0x42, 0x75, 0x74, 0x74, 0x6f, 0x6e, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x22,
	0x68, 0x0a, 0x04, 0x48, 0x6f, 0x6d, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x68, 0x6f, 0x6d, 0x65, 0x4c,
	0x6f, 0x67, 0x6f, 0x50, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x68,
	0x6f, 0x6d, 0x65, 0x4c, 0x6f, 0x67, 0x6f, 0x50, 0x61, 0x74, 0x68, 0x12, 0x1a, 0x0a, 0x08, 0x68,
	0x6f, 0x6d, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x68,
	0x6f, 0x6d, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x68, 0x6f, 0x6d, 0x65, 0x42,
	0x67, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x68, 0x6f,
	0x6d, 0x65, 0x42, 0x67, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x22, 0x30, 0x0a, 0x12, 0x41, 0x64, 0x64,
	0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x71, 0x12,
	0x1a, 0x0a, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x22, 0x4e, 0x0a, 0x14, 0x47,
	0x65, 0x74, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4f, 0x76, 0x65, 0x72, 0x76, 0x69, 0x65, 0x77,
	0x52, 0x65, 0x71, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x44, 0x61, 0x74, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x44, 0x61, 0x74,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x6e, 0x64, 0x44, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x65, 0x6e, 0x64, 0x44, 0x61, 0x74, 0x65, 0x22, 0x4b, 0x0a, 0x11, 0x47,
	0x65, 0x74, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x54, 0x72, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x71,
	0x12, 0x1c, 0x0a, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x44, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x44, 0x61, 0x74, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x65, 0x6e, 0x64, 0x44, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x65, 0x6e, 0x64, 0x44, 0x61, 0x74, 0x65, 0x22, 0x36, 0x0a, 0x1e, 0x47, 0x65, 0x74, 0x43,
	0x75, 0x6d, 0x75, 0x6c, 0x61, 0x74, 0x69, 0x76, 0x65, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4f,
	0x76, 0x65, 0x72, 0x76, 0x69, 0x65, 0x77, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6e,
	0x64, 0x41, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6e, 0x64, 0x41, 0x74,
	0x22, 0x56, 0x0a, 0x12, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4f, 0x76, 0x65, 0x72, 0x76, 0x69,
	0x65, 0x77, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x2a, 0x0a, 0x10,
	0x70, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x4f, 0x76, 0x65, 0x72, 0x70, 0x65, 0x72, 0x69, 0x6f, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x10, 0x70, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x4f, 0x76,
	0x65, 0x72, 0x70, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x22, 0xf1, 0x01, 0x0a, 0x12, 0x43, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x4f, 0x76, 0x65, 0x72, 0x56, 0x69, 0x65, 0x77, 0x49, 0x6e, 0x66, 0x6f, 0x12,
	0x47, 0x0a, 0x0c, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x65, 0x5f,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4f, 0x76,
	0x65, 0x72, 0x76, 0x69, 0x65, 0x77, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x0c, 0x61, 0x63, 0x74, 0x69,
	0x76, 0x65, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x12, 0x45, 0x0a, 0x0b, 0x74, 0x6f, 0x74, 0x61,
	0x6c, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e,
	0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4f, 0x76, 0x65, 0x72, 0x76, 0x69, 0x65, 0x77, 0x49, 0x74,
	0x65, 0x6d, 0x52, 0x0b, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x12,
	0x4b, 0x0a, 0x0e, 0x61, 0x64, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74,
	0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x4f, 0x76, 0x65, 0x72, 0x76, 0x69, 0x65, 0x77, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x0e, 0x61, 0x64,
	0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x22, 0x4a, 0x0a, 0x0f,
	0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x54, 0x72, 0x65, 0x6e, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x12,
	0x37, 0x0a, 0x06, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1f, 0x2e, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x43, 0x68, 0x61, 0x72, 0x74,
	0x52, 0x06, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x22, 0x73, 0x0a, 0x0e, 0x53, 0x74, 0x61, 0x74,
	0x69, 0x73, 0x74, 0x69, 0x63, 0x43, 0x68, 0x61, 0x72, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x61,
	0x62, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74,
	0x61, 0x62, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x43, 0x0a, 0x0a, 0x63, 0x68, 0x61, 0x72,
	0x74, 0x4c, 0x69, 0x6e, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x6f,
	0x70, 0x65, 0x72, 0x61, 0x74, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x53,
	0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x43, 0x68, 0x61, 0x72, 0x74, 0x4c, 0x69, 0x6e,
	0x65, 0x52, 0x0a, 0x63, 0x68, 0x61, 0x72, 0x74, 0x4c, 0x69, 0x6e, 0x65, 0x73, 0x22, 0x6f, 0x0a,
	0x12, 0x53, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x43, 0x68, 0x61, 0x72, 0x74, 0x4c,
	0x69, 0x6e, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x69, 0x6e, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x69, 0x6e, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x3d, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x27,
	0x2e, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x53, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x43, 0x68, 0x61, 0x72, 0x74, 0x4c,
	0x69, 0x6e, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x22, 0x40,
	0x0a, 0x16, 0x53, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x43, 0x68, 0x61, 0x72, 0x74,
	0x4c, 0x69, 0x6e, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x32, 0x8f, 0x06, 0x0a, 0x0e, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x65, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x5c, 0x0a, 0x15, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x79, 0x73,
	0x74, 0x65, 0x6d, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x54, 0x61, 0x62, 0x12, 0x29, 0x2e, 0x6f,
	0x70, 0x65, 0x72, 0x61, 0x74, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x43, 0x75, 0x73, 0x74, 0x6f,
	0x6d, 0x54, 0x61, 0x62, 0x52, 0x65, 0x71, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22,
	0x00, 0x12, 0x60, 0x0a, 0x17, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x79, 0x73, 0x74, 0x65,
	0x6d, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x2b, 0x2e, 0x6f,
	0x70, 0x65, 0x72, 0x61, 0x74, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x43, 0x75, 0x73, 0x74, 0x6f,
	0x6d, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74,
	0x79, 0x22, 0x00, 0x12, 0x5e, 0x0a, 0x16, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x79, 0x73,
	0x74, 0x65, 0x6d, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x48, 0x6f, 0x6d, 0x65, 0x12, 0x2a, 0x2e,
	0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x43, 0x75, 0x73, 0x74,
	0x6f, 0x6d, 0x48, 0x6f, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74,
	0x79, 0x22, 0x00, 0x12, 0x57, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d,
	0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x12, 0x23, 0x2e, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x65,
	0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x79, 0x73, 0x74,
	0x65, 0x6d, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x52, 0x65, 0x71, 0x1a, 0x1d, 0x2e, 0x6f, 0x70,
	0x65, 0x72, 0x61, 0x74, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x53, 0x79,
	0x73, 0x74, 0x65, 0x6d, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x22, 0x00, 0x12, 0x50, 0x0a, 0x0f,
	0x41, 0x64, 0x64, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x12,
	0x23, 0x2e, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x41, 0x64, 0x64, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x72,
	0x64, 0x52, 0x65, 0x71, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x61,
	0x0a, 0x11, 0x47, 0x65, 0x74, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4f, 0x76, 0x65, 0x72, 0x76,
	0x69, 0x65, 0x77, 0x12, 0x25, 0x2e, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x65, 0x5f, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4f,
	0x76, 0x65, 0x72, 0x76, 0x69, 0x65, 0x77, 0x52, 0x65, 0x71, 0x1a, 0x23, 0x2e, 0x6f, 0x70, 0x65,
	0x72, 0x61, 0x74, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x43, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x4f, 0x76, 0x65, 0x72, 0x56, 0x69, 0x65, 0x77, 0x49, 0x6e, 0x66, 0x6f, 0x22,
	0x00, 0x12, 0x58, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x54, 0x72,
	0x65, 0x6e, 0x64, 0x12, 0x22, 0x2e, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x65, 0x5f, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x54,
	0x72, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x1a, 0x20, 0x2e, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74,
	0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x54, 0x72, 0x65, 0x6e, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x00, 0x12, 0x75, 0x0a, 0x1b, 0x47,
	0x65, 0x74, 0x43, 0x75, 0x6d, 0x75, 0x6c, 0x61, 0x74, 0x69, 0x76, 0x65, 0x43, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x4f, 0x76, 0x65, 0x72, 0x76, 0x69, 0x65, 0x77, 0x12, 0x2f, 0x2e, 0x6f, 0x70, 0x65,
	0x72, 0x61, 0x74, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x47, 0x65, 0x74,
	0x43, 0x75, 0x6d, 0x75, 0x6c, 0x61, 0x74, 0x69, 0x76, 0x65, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x4f, 0x76, 0x65, 0x72, 0x76, 0x69, 0x65, 0x77, 0x52, 0x65, 0x71, 0x1a, 0x23, 0x2e, 0x6f, 0x70,
	0x65, 0x72, 0x61, 0x74, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x43, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x4f, 0x76, 0x65, 0x72, 0x56, 0x69, 0x65, 0x77, 0x49, 0x6e, 0x66, 0x6f,
	0x22, 0x00, 0x42, 0x35, 0x5a, 0x33, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x55, 0x6e, 0x69, 0x63, 0x6f, 0x6d, 0x41, 0x49, 0x2f, 0x77, 0x61, 0x6e, 0x77, 0x75, 0x2f,
	0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74,
	0x65, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_proto_operate_service_operate_service_proto_rawDescOnce sync.Once
	file_proto_operate_service_operate_service_proto_rawDescData = file_proto_operate_service_operate_service_proto_rawDesc
)

func file_proto_operate_service_operate_service_proto_rawDescGZIP() []byte {
	file_proto_operate_service_operate_service_proto_rawDescOnce.Do(func() {
		file_proto_operate_service_operate_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_operate_service_operate_service_proto_rawDescData)
	})
	return file_proto_operate_service_operate_service_proto_rawDescData
}

var file_proto_operate_service_operate_service_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_proto_operate_service_operate_service_proto_goTypes = []interface{}{
	(*CreateSystemCustomTabReq)(nil),       // 0: operate_service.CreateSystemCustomTabReq
	(*CreateSystemCustomLoginReq)(nil),     // 1: operate_service.CreateSystemCustomLoginReq
	(*CreateSystemCustomHomeReq)(nil),      // 2: operate_service.CreateSystemCustomHomeReq
	(*GetSystemCustomReq)(nil),             // 3: operate_service.GetSystemCustomReq
	(*SystemCustom)(nil),                   // 4: operate_service.SystemCustom
	(*Tab)(nil),                            // 5: operate_service.Tab
	(*Login)(nil),                          // 6: operate_service.Login
	(*Home)(nil),                           // 7: operate_service.Home
	(*AddClientRecordReq)(nil),             // 8: operate_service.AddClientRecordReq
	(*GetClientOverviewReq)(nil),           // 9: operate_service.GetClientOverviewReq
	(*GetClientTrendReq)(nil),              // 10: operate_service.GetClientTrendReq
	(*GetCumulativeClientOverviewReq)(nil), // 11: operate_service.GetCumulativeClientOverviewReq
	(*ClientOverviewItem)(nil),             // 12: operate_service.ClientOverviewItem
	(*ClientOverViewInfo)(nil),             // 13: operate_service.ClientOverViewInfo
	(*ClientTrendInfo)(nil),                // 14: operate_service.ClientTrendInfo
	(*StatisticChart)(nil),                 // 15: operate_service.StatisticChart
	(*StatisticChartLine)(nil),             // 16: operate_service.StatisticChartLine
	(*StatisticChartLineItem)(nil),         // 17: operate_service.StatisticChartLineItem
	(*emptypb.Empty)(nil),                  // 18: google.protobuf.Empty
}
var file_proto_operate_service_operate_service_proto_depIdxs = []int32{
	5,  // 0: operate_service.CreateSystemCustomTabReq.tab:type_name -> operate_service.Tab
	6,  // 1: operate_service.CreateSystemCustomLoginReq.login:type_name -> operate_service.Login
	7,  // 2: operate_service.CreateSystemCustomHomeReq.home:type_name -> operate_service.Home
	6,  // 3: operate_service.SystemCustom.login:type_name -> operate_service.Login
	5,  // 4: operate_service.SystemCustom.tab:type_name -> operate_service.Tab
	7,  // 5: operate_service.SystemCustom.home:type_name -> operate_service.Home
	12, // 6: operate_service.ClientOverViewInfo.activeClient:type_name -> operate_service.ClientOverviewItem
	12, // 7: operate_service.ClientOverViewInfo.totalClient:type_name -> operate_service.ClientOverviewItem
	12, // 8: operate_service.ClientOverViewInfo.additionClient:type_name -> operate_service.ClientOverviewItem
	15, // 9: operate_service.ClientTrendInfo.client:type_name -> operate_service.StatisticChart
	16, // 10: operate_service.StatisticChart.chartLines:type_name -> operate_service.StatisticChartLine
	17, // 11: operate_service.StatisticChartLine.items:type_name -> operate_service.StatisticChartLineItem
	0,  // 12: operate_service.OperateService.CreateSystemCustomTab:input_type -> operate_service.CreateSystemCustomTabReq
	1,  // 13: operate_service.OperateService.CreateSystemCustomLogin:input_type -> operate_service.CreateSystemCustomLoginReq
	2,  // 14: operate_service.OperateService.CreateSystemCustomHome:input_type -> operate_service.CreateSystemCustomHomeReq
	3,  // 15: operate_service.OperateService.GetSystemCustom:input_type -> operate_service.GetSystemCustomReq
	8,  // 16: operate_service.OperateService.AddClientRecord:input_type -> operate_service.AddClientRecordReq
	9,  // 17: operate_service.OperateService.GetClientOverview:input_type -> operate_service.GetClientOverviewReq
	10, // 18: operate_service.OperateService.GetClientTrend:input_type -> operate_service.GetClientTrendReq
	11, // 19: operate_service.OperateService.GetCumulativeClientOverview:input_type -> operate_service.GetCumulativeClientOverviewReq
	18, // 20: operate_service.OperateService.CreateSystemCustomTab:output_type -> google.protobuf.Empty
	18, // 21: operate_service.OperateService.CreateSystemCustomLogin:output_type -> google.protobuf.Empty
	18, // 22: operate_service.OperateService.CreateSystemCustomHome:output_type -> google.protobuf.Empty
	4,  // 23: operate_service.OperateService.GetSystemCustom:output_type -> operate_service.SystemCustom
	18, // 24: operate_service.OperateService.AddClientRecord:output_type -> google.protobuf.Empty
	13, // 25: operate_service.OperateService.GetClientOverview:output_type -> operate_service.ClientOverViewInfo
	14, // 26: operate_service.OperateService.GetClientTrend:output_type -> operate_service.ClientTrendInfo
	13, // 27: operate_service.OperateService.GetCumulativeClientOverview:output_type -> operate_service.ClientOverViewInfo
	20, // [20:28] is the sub-list for method output_type
	12, // [12:20] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_proto_operate_service_operate_service_proto_init() }
func file_proto_operate_service_operate_service_proto_init() {
	if File_proto_operate_service_operate_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_operate_service_operate_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateSystemCustomTabReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_operate_service_operate_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateSystemCustomLoginReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_operate_service_operate_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateSystemCustomHomeReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_operate_service_operate_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSystemCustomReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_operate_service_operate_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SystemCustom); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_operate_service_operate_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Tab); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_operate_service_operate_service_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Login); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_operate_service_operate_service_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Home); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_operate_service_operate_service_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddClientRecordReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_operate_service_operate_service_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetClientOverviewReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_operate_service_operate_service_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetClientTrendReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_operate_service_operate_service_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCumulativeClientOverviewReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_operate_service_operate_service_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientOverviewItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_operate_service_operate_service_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientOverViewInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_operate_service_operate_service_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientTrendInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_operate_service_operate_service_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StatisticChart); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_operate_service_operate_service_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StatisticChartLine); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_operate_service_operate_service_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StatisticChartLineItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_operate_service_operate_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_operate_service_operate_service_proto_goTypes,
		DependencyIndexes: file_proto_operate_service_operate_service_proto_depIdxs,
		MessageInfos:      file_proto_operate_service_operate_service_proto_msgTypes,
	}.Build()
	File_proto_operate_service_operate_service_proto = out.File
	file_proto_operate_service_operate_service_proto_rawDesc = nil
	file_proto_operate_service_operate_service_proto_goTypes = nil
	file_proto_operate_service_operate_service_proto_depIdxs = nil
}
